/*!
 * \file
 * \ingroup base
 * \author  Stefan M. Trenkwalder <s.trenkwalder@openswarm.org>
 * \version 1.0
 *
 * \date{07 July 2014}
 * 
 * \brief It declares functions to initialise and start OpenSwarm.
 * \copyright 	adapted FreeBSD License (see http://openswarm.org/license)
 */

/*! \mainpage OpenSwarm documentation
 * \image html "../doc/img/openswarm_logo.png"
 *
 * \section intro_sec Introduction
 * OpenSwarm is an easy-to-use event-driven preemptive operating system for miniature robots. It offers abstract hardware-independent functions to make user code more extendible, maintainable, and portable.
 * The hybrid kernel provides preemptive and cooperative scheduling, asynchronous and synchronous programming models with events, and inter-process communication functions. \n\n  
 * OpenSwarm was created during the PhD of Stefan M Trenkwalder (http://trenkwalder.tech) at the University of Sheffield (http://www.sheffield.ac.uk/) under the Supervision of Dr. Roderich Gross and Dr. Andreas Kolling. 
 * 
 * The code of OpenSwarm can be basically divided into 3 different modules:
 * - \ref process
 * - \ref events
 * - \ref io (This includes device specific sensors and actuators)
 * 
 * All modules are, then, combined in OpenSwarm's \ref base . 
 * 
 * \htmlonly
 * \section brief_dec Documentation Structure
 * This documentation was generated by Doxygen (http://www.doxygen.org) and is structured as follows
 * - Main Page: This tab represents a short introduction to and general comments on OpenSwarm
 * - Modules: This tab presents a list of logical units of OpenSwarm (such as Process Management or Event System)
 * - Data Structures: This tab shows a list of all used data structures inside OpenSwarm.
 * - Files: This tab lists the documentation of each individual file in OpenSwarm.
 * \endhtmlonly
 * 
 * \section link_sec Links
 * - http://www.openswarm.org/          	The official OpenSwarm website
 * - http://trenkwalder.tech/   		The academic webpage of Stefan Trenkwalder
 * - http://naturalrobotics.group.shef.ac.uk/   The website of the research group 
 * - http://openswarm.org/license/              The link to the newest license (in case it changed)
 *  
 * \section base_license License
 * LICENSE: adapted FreeBSD License (see http://openswarm.org/license)\n
 * Copyright (c) 2015, Stefan M. Trenkwalder\n
 * All rights reserved. 
 * 
 * \section base_thanks Thanks
 * OpenSwarm is part of the PhD of Stefan M. Trenkwalder (http://trenkwalder.tech) who is recipient of a DOC Fellowship of the Austrian Academy of Sciences (http://www.oeaw.ac.at/).
 */

/*! \defgroup base Kernel
 * \brief OpenSwarm provides functions to start and initialise the operating system; allocate, free and copy memory; and create and end atomic sections.
 * 
 * \author  Stefan M. Trenkwalder <s.trenkwalder@openswarm.org>
 * 
 * \section sec_intro_base Introduction
 * The Kernel contains basic functions to initialise and start all modules of OpenSwarm. This part of OpenSwarm executes all three modules
 *  -# \ref process
 *  -# \ref events
 *  -# \ref io
 *
 * 
 * First, the system has to be configured by setting preprocessor values and variables. Then, OpenSwarm initialises the system and I/O according to its configuration (preprocessor definitions) and with an additional command the system can be started. In addition, functions to define atomic sections (sections that cannot be interrupted by anything), allocate and free memory are also provided. 
 * 
 * \subsection ssec_intro_base_defs Definitions  
 * definition.h provides standardised ports, configures the used platform, and defines general preprocessor/type definitions that are needed in OpenSwarm.
 * 
 * \subsection ssec_intro_base_mem Memory Management  
 * OpenSwarm is designed for processing units that lack a MMU (Memory Management Unit). As a consequence, advance memory management functions as virtual memory cannot be implemented without a significant reduction of efficiency. 
 * 
 * However, OpenSwarm provides atomic functions to allocate, free and copy memory in memory.h.
 * 
 * \subsection ssec_intro_base_irq Interrupt Management  
 * OpenSwarm provides defined interrupt priorities and functions to create atomic sections in interrupts.h. A atomic section is a section of code that cannot be interrupted.
 * 
 */

#include "definitions.h"

#ifdef EPUCK_USED
#define SYS_MOTOR_USED	 	/*!< Define this preprocessor symbol to use motors */
#define SYS_UART1_USED		 /*!< Define this preprocessor symbol to use UART1 */
#define SYS_REMOTECONTROL_USED	 /*!< Define this preprocessor symbol to receive remote control signals */
#define SYS_CAMERA_USED		 /*!< Define this preprocessor symbol to use the camera */
#endif

#include "io/io.h"
#include "events/events.h"
#include "processes/process_Management.h"

void Sys_Init_Kernel(void);   //initialises the hardware
void Sys_Start_Kernel(void);    //starts all needed functions
